// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkbhXxkPWUVdaQ9LINKd3HTcmiwukmT_o',
    appId: '1:255703932908:web:2a0fe1c76d62ce0fdc6ac9',
    messagingSenderId: '255703932908',
    projectId: 'flutter-ecommerce-fe53c',
    authDomain: 'flutter-ecommerce-fe53c.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-fe53c.appspot.com',
    measurementId: 'G-LT05F10XN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzoQQf_HW3B4cWITPyeO1T6Bydu-LCh34',
    appId: '1:255703932908:android:6a7a25b9581256b7dc6ac9',
    messagingSenderId: '255703932908',
    projectId: 'flutter-ecommerce-fe53c',
    storageBucket: 'flutter-ecommerce-fe53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqq2uZBecP6YQRPVDFUIVLpFGwDUC23k',
    appId: '1:255703932908:ios:f4f49a02f67cc6dadc6ac9',
    messagingSenderId: '255703932908',
    projectId: 'flutter-ecommerce-fe53c',
    storageBucket: 'flutter-ecommerce-fe53c.appspot.com',
    iosClientId: '255703932908-6cf58eku6dg1m5egl7ffft52bc50tkva.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqq2uZBecP6YQRPVDFUIVLpFGwDUC23k',
    appId: '1:255703932908:ios:f4f49a02f67cc6dadc6ac9',
    messagingSenderId: '255703932908',
    projectId: 'flutter-ecommerce-fe53c',
    storageBucket: 'flutter-ecommerce-fe53c.appspot.com',
    iosClientId: '255703932908-6cf58eku6dg1m5egl7ffft52bc50tkva.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
